### ISSUE TITLE
orm + cohttp

### ISSUE THREAD

**Issue by Ulrar** [mirage/orm#12]
Hi,

I might be missing something huge, but as far as I can tell orm and cohttp aren't compatible with each other, even though they're both from the mirage project.
orm requires camlp4o to compile (or "with orm" doesn't work), and cohttp can't have camlp4o enabled or it's ~mode: when creating a server is an error, since mode is a keyword.

Is there no way to have both in the same project ? I'm not usually an ocaml user, so that might be me.
Bonus question, is there any kind of doc for orm ? I've been figuring it out using the tests in lib_test, but that's really not ideal.

Thanks !

**Comment by samoht** [comment]
Hi there. Unfortunately `orm` is a very old project which was created when ppx didn't even exist and so it is based on camlp4. Since then, the OCaml community deprecated camp4 and use ppx instead but `orm` hasn't moved.

So it would be an interesting exercice to port `orm` to the ppx mechanism, but I am not sure who has the motivation nor time to do this. In any case, if you are interested, please feel free to submit pull requests :-)

**Comment by Ulrar** [comment]
Ah, I understand. Thanks for the reply, might be nice to add a little note on this repo then.
I'll use something else I guess !
